name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: ${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        target:
          - ubuntu-latest
    runs-on: ${{ matrix.target }}
    steps:
    - uses: actions/checkout@v3

    - name: Install devscripts
      run: |
        sudo apt -qq update
        sudo apt -y dist-upgrade
        sudo DEBIAN_FRONTEND=noninteractive apt install -qq devscripts equivs lintian
        mk-build-deps -i -s sudo -t "apt --yes --no-install-recommends"

    - name: Build source package
      env:
        DEBFULLNAME: "Jakob Flierl"
        DEBEMAIL: "jakob.flierl@gmail.com"
      run: |
        export TARGET=$(. /etc/lsb-release && echo $DISTRIB_CODENAME)
        git fetch --unshallow
        git fetch --tags
        VERSION="$(git tag -l | tail -n1 | sed -e "s/^v//" -e "s/-/+git/")"
        dch --create \
            --distribution ${TARGET} \
            --package libqgcodeeditor \
            --newversion ${VERSION}~${TARGET}1 \
            "Automatic build from Github"
        debuild -S -sa -us -uc -d

    - name: Build deb packages
      run: |
        dpkg-buildpackage -b -rfakeroot -us -uc

    - name: Install deb packages
      run: |
        sudo dpkg -i ../libqgcodeeditor*deb
        sudo apt -y -f install

    - name: Run lintian
      run: |
        lintian ../libqgcodeeditor*deb | lintian-info

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.target }}
        if-no-files-found: error
        path: |
          *.buildinfo
          *.changes
          *.dsc
          *.tar.*
          *.deb
          ~/**/*/*.buildinfo
          ~/**/*/*.changes
          ~/**/*/*.dsc
          ~/**/*/*.tar.*
          ~/**/*/*.deb
